name: Deploy to Azure

on:
  push:
    branches:
      - main  # or change this to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Build project
        run: npm run build
        working-directory: frontend

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: YARA
          package: frontend/build
